services:
  ewelink-server:
    build:
      context: ./ewelink-server
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ewelink_data:/usr/src/app/data

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
      - WEBHOOK_TUNNEL_URL=http://localhost:5678
      - TZ=America/Sao_Paulo  # Defina o timezone desejado aqui
      - N8N_SECURE_COOKIE=false
      - OLLAMA_HOST=host.docker.internal
      - OLLAMA_PORT=11434  # Porta usada pelo seu Ollama

    restart: always
    volumes:
      - ./n8n_data:/root/.n8n
    depends_on:
      - ewelink-server

volumes:
  ewelink_data:
    driver: local
  n8n_data:
    driver: local